title: bitcoin Signet | PSA - they are worthless
tagline: Bitcoin Signet coins are worthless. Here is how to stay safe and not get scammed
description: Bitcoin Signet Public Service Announcement. Bitcoin Signet coins are intentionally worthless. Bitcoin Signet is a test Bitcoin network, used for testing and educational purposes. This is a feature of Bitcoin, not a bug. If you're being offered "Free" or "Discount" bitcoin and promised they are real bitcoin, they may be worthless Bitcoin Signet coins. You may be cheated for your time and/or money. Here is how to stay safe.
url: https://www.bitcoinsignet.com
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
